extends Node

const ID = "core.icons"
const HOME = preload("res://Icons/Home.svg")
const CHECKBOOK = preload("res://Icons/CheckBook.svg")
const CHECKLIST = preload("res://Icons/Checklist.svg")
const TRASH = preload("res://Icons/Trash.svg")
const LEFT = preload("res://Icons/Left.svg")
const RIGHT = preload("res://Icons/Right.svg")
const SCISSORS = preload("res://Icons/Scissors.svg")
const UP = preload("res://Icons/Up.svg")
const DOWN = preload("res://Icons/DOWN.svg")
const TERMINAL = preload("res://Icons/Terminal.svg")
const CODE = preload("res://Icons/Code.svg")
const X = preload("res://Icons/X.svg")
const USER = preload("res://Icons/User.svg")
const PALETTE = preload("res://Icons/Palette.svg")
const PERSON = preload("res://Icons/Person.svg")
const GEAR = preload("res://Icons/Gear.svg")
const PUZZLE = preload("res://Icons/Puzzle.svg")
const SEARCH = preload("res://Icons/Search.svg")
const SQUAREX = preload("res://Icons/SquareX.svg")
const PAPERPLANE = preload("res://Icons/PaperPlane.svg")
const PENCIL = preload("res://Icons/Pencil.svg")
const ERASER = preload("res://Icons/Eraser.svg")
const WARNING = preload("res://Icons/Warning.svg")
const LOCK = preload("res://Icons/Lock.svg")
const DOWNARROWCIRCLE = preload("res://Icons/DownArrowCircle.svg")
const TOGGLE = preload("res://Icons/Toggle.svg")
const FLASK = preload("res://Icons/Flask.svg")
const BELL = preload("res://Icons/Bell.svg")
const UNDO = preload("res://Icons/Undo.svg")
const REDO = preload("res://Icons/Redo.svg")
const COPY = preload("res://Icons/Copy.svg")
const CLIPBOARD = preload("res://Icons/Clipboard.svg")
const TEXTCURSOR = preload("res://Icons/TextCursor.svg")
const QUSETIONCIRCLE = preload("res://Icons/QuestionCircle.svg")
const FOLDER = preload("res://Icons/Folder.svg")
const REFRESH = preload("res://Icons/Refresh.svg")
const DOWNLOAD = preload("res://Icons/Download.svg")
const THREEDOTS = preload("res://Icons/ThreeDots.svg")
const FILETEXT = preload("res://Icons/FileText.svg")
const BLOCKS = preload("res://Icons/Blocks.svg")
const SHIELDCHECK = preload("res://Icons/ShieldCheck.svg")

func get_icon_path(icon:String) -> String:
	var path = "res://Icons/"+icon+".svg"
	if !ResourceLoader.exists(path):
		Debug.warn("A process attempted to get the path of an icon that does not exist, check the icon name and try again. Icon Name: "+icon,ID)
		return ""
	return path
